application:
  name: Comparison App
  description: test application for comparison scenarios
  location: apps/comparison_app/bootstrap.rb
  type: singular
  plugins:
   - location: plugins/sysstats_plugin/plugin.rb
    #location: plugins/repose_jmx_plugin/plugin.rb
    #location: plugins/postgres/plugin.rb
    #location: plugins/atom_feed/plugin.rb
    #location: plugins/atom_graphite/plugin.rb
  sub_apps: 
   - 
     id: main
     name: Main application
     description: This is the base configuration for Atom Hopper
