---
application:
  name: Before After Plugin for Singular apps
  description: 
  location: apps/before_after_singular/bootstrap.rb
  type: singular
  plugins:
   - location: plugins/before_after_plugin/plugin.rb
  sub_apps:
  - id: main
    name: Main
    description:
