redis:
  host: localhost
  port: 6379
  db: 1
file_store: localhost:3000  
storage_info:
  destination: localhost
  user: dimi5963
  path: /Users/dimi5963/projects/lighttpd/data
  prefix: files
test_list:
  load_test:
    name: Load Test
    description: Test running for a sample duration at 120% of expected load for the application.
  duration_test:
    name: Duration Test
    description: Test running for a a longer duration than average (optimally 12 to 48 hours at 75% expected load)
  stress_test:
    name: Stress Test
    description: Test running with constant increasing load until application fails
  adhoc_test:
    name: Adhoc Test
    description: Test with custom settings.  A one-time only iteration